import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

const SECTIONS = [
  {
    title: "What we collect",
    body: "Account details you provide directly (name, email, blood type or facility name), plus activity data generated by using the platform — requests posted, responses confirmed, and donation records.",
  },
  {
    title: "How we use it",
    body: "To match compatible donors to nearby requests, to maintain an accurate donation history for both donors and facilities, and to notify you about requests relevant to your blood type and location.",
  },
  {
    title: "What we don't do",
    body: "We don't sell donor or facility data to third parties, and hospitals never see a donor's identity or contact details until that donor chooses to respond to a specific request.",
  },
  {
    title: "Health information handling",
    body: "Blood type and donation history are treated as sensitive health information. Access is limited to what's operationally necessary to run the matching and inventory features described on this platform.",
  },
  {
    title: "Data retention & deletion",
    body: "You can request deletion of your account from your profile at any time. Records tied to completed donations may be retained longer where required for facility audit or compliance purposes.",
  },
  {
    title: "Your choices",
    body: "You can update your profile information at any time, and you can contact us to ask what data we hold about you.",
  },
];

export default function Privacy() {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      <main className="flex-1">
        <section className="pt-24 pb-12 bg-background">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-3xl">
            <p className="text-sm font-medium text-primary uppercase tracking-widest mb-6">Legal</p>
            <h1 className="text-4xl md:text-5xl font-serif font-bold leading-[1.1] mb-6">Privacy Policy</h1>
            <p className="text-muted-foreground leading-relaxed">
              This page describes, in plain language, what Blood Bridge collects and how it's used. It's a working draft for this build and should be reviewed by counsel before any production launch handling real health data.
            </p>
          </div>
        </section>

        <section className="pb-24 bg-background">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-3xl divide-y divide-border">
            {SECTIONS.map((s) => (
              <div key={s.title} className="py-8 first:pt-0 last:pb-0">
                <h2 className="text-xl font-serif font-bold mb-3">{s.title}</h2>
                <p className="text-muted-foreground leading-relaxed">{s.body}</p>
              </div>
            ))}
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
